# Default values for chaosblade.

# chaosblade-operator
operator:
  repository: keke001/chaosblade-operator
  version: 1.8.7

  # image.pullPolicy: must be Always|IfNotPresent|Never
  pullPolicy: IfNotPresent
  # qps of kubernetes client
  qps: 20
  reconcileCount: 20

blade:
  repository: keke001/chaosblade-tool
  version: 1.8.7
  pullPolicy: IfNotPresent
  downloadUrl: ""

env:
  logLevel: info

webhook:
  enable: true

daemonset:
  enable: true

remove:
  blade:
    interval: 72h

network:
  host: false
  dns:
    policy: ClusterFirst
